### ISSUE TITLE
Generic Story Manager Proposal

### ISSUE THREAD

**Issue by willnationsdev** [rakugoteam/Rakugo-archive#133]
# Preface:

So, I've chatted with @jebedaia360 previously, and at the time, it seemed like Rakugo was just gonna be a RenPy wrapper/clone in GDScript. Now, from what I've heard from @BurningWood, it intends to become more generic than that.

I'm not familiar with RenPy very much though I've read some docs. I also haven't spent a lot of time yet in Rakugo's source code. However, from what I have seen, there are some systemic issues that the devs are trying to confront.

I would like to offer suggestions on what I personally envision for a generic, robust, and powerful story system that can apply to any potential game. If these suggestions are desirable/acceptable to integrate into this plugin, then let me know and I'd like to offer myself as a design consultant / contributor (when I can find the time). If not, then that's cool, and I'll just reserve my ideas for `godot-journey`. Would prefer not to divide up our efforts though if they fall in line, hence this proposal Issue (won't even need `godot-journey` if the effort can be done here).

I'll be clear: if we did *everything* I propose, it would probably entail rewriting very large portions of the Rakugo codebase (by my guess) and re-organizing it into multiple repositories. So...this kind of decision isn't to be taken lightly. XD I just wanna broach the possibility of working together rather than separately.

willnationsdev/godot-journey#1

This is what I envision for `godot-journey`. It would serve as a basis for any and all future story management plugins as other plugins would merely create a particular visualization - like Rakugo's Phone Mode, or interface - like Rakugo's GDScript API or future RakugoScript, etc. and add to the available ways of interacting with the Core.

If you'd like, we could continue going down this route where people work on both `godot-journey` and `Rakugo` and essentially keep `godot-journey` as the Core repository and then once it is far enough along, Rakugo can just refactor to build on top of it. Let me know what you think.

**Comment by willnationsdev** [comment]
cc @xDGameStudios

**Comment by Jeremi360** [comment]
@willnationsdev 
willnationsdev/godot-journey#1 is huge and you are awesome and crazy genius.
I very like your ideas for godot-journey :D
So we work on both `godot-journey` and `Rakugo`
and when `godot-journey` is ready we rewrite `Rakugo` to use it.

**Comment by Jeremi360** [comment]
@willnationsdev @xDGameStudios here is Rakugo's dev discord channel: https://discord.gg/EK3VQpj

**Comment by Jeremi360** [comment]
There is no need for this issue to be open.
