### ISSUE TITLE
Rakugo's plugin.gd doesn't work - how to set up Rakugo?

### ISSUE THREAD

**Issue by Sslaxx** [rakugoteam/Rakugo-archive#153]
This is using Godot 3.1.1. Rakugo commit https://github.com/jebedaia360/Rakugo/commit/33b09b6685289f0e3aabf0254064a76b814575c7

Putting the Rakugo addon in place, it can't be activated as a plugin because it gives the error `Unable to load addon script from path: 'res://addons/Rakugo/plugin.gd' There appears to be an error in the code, please check the syntax.`

This is because of its use of directories outside of `res://addons/Rakugo`.

https://rakugo.readthedocs.io/en/latest/config/ implies using singletons to activate Rakugo. It's fairly clear that just using `addons` doesn't work. It'd be nice if Rakugo's files were self-contained within `addons/Rakugo`.

There is a separate issue with Godot's default error messages about plugin activation being less than helpful unless you look at the command line, going to be filing one if needed.

**Comment by Jeremi360** [comment]
This is not cossider as error - for now Rakugo can be only use as game template, and probably it wan't change soon or maybe never
