### ISSUE TITLE
Rakugo 2.0.2 crashing when text contains color keyword

### ISSUE THREAD

**Issue by Nareion** [rakugoteam/Rakugo-archive#157]
When writing dialog in renpy markup, any text containing words like "red" or "fired" crashes with  the following error in types/rakugo_color.gd line 561

> Invalid call. Nonexistent function 'to_html' in base 'String'.

This was tested both for renpy and bbcode markup.

### Steps to reproduce:

In a clean project, create a new scene and set the following as script:

```
extends Node

func _ready():
	if Rakugo.current_root_node != self:
		Rakugo.current_root_node = self
	Rakugo.say({"who": "Apptester", "what": "Testing red"})
```

**Comment by Jeremi360** [comment]
Thanks for info @Nareion .
I just fixed it with this commit https://github.com/jebedaia360/Rakugo/commit/dfdc8b9f7421703304bc4f4460d8a72c70743237
I will do next release with this and some other fixes today.
