### ISSUE TITLE
Add .import folder to .gitignore

### ISSUE THREAD

**Issue by TheDuriel** [rakugoteam/Rakugo-archive#159]
Should not be committed. It can be rebuilt from source assets and just slows down pulling. Will also conflict with users .import folder, and most likely rebuild _anyways_.

**Comment by Jeremi360** [comment]
Do you download it all a you use it as base for your game project?

It was in .gitignore, but I and @BurningWood notice that it take long time for rebuilt _.import_ folder so I removed it. And I don't have many regular contributors, so I don't have enough test data for problems like this. If you say that it rebuild then I will remove it, by I checked it on other computers and form me committing _,import_ saves time - it only rebuilt small parts for _.import_ .

PS 2.  I see you done some time a go https://github.com/TheDuriel/YouHaveATree do you want to port it to Rakugo? I need help with Visual Scripting for Rakugo, I don't know how to do it by myself.

PS 3. Join my discord to: https://discord.gg/bCb8dV

**Comment by Jeremi360** [comment]
that is strange, is still commits it self, but it is added to [.gitignore](https://github.com/rakugoteam/Rakugo/blob/master/.gitignore)

Probably I must do `git rm *.import -- cached`
And change it to `*.import`
