### ISSUE TITLE
Save / Load Game 

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/Rakugo-archive#17]
Saving/Load like in Ren'Py:
![](https://www.renpy.org/doc/html/_images/slot_save.jpg)

**Comment by Jeremi360** [comment]
simple Quick Load\Save works for visual script verison

**Comment by deep-gaurav** [comment]
Slot Save/Load woks too in VS now,

**Comment by Jeremi360** [comment]
Now we try write new save/load system using `PackedScene`.

**Comment by Jeremi360** [comment]
@MatiasVME  Now it almost works (only text mode) using PersistenceNode,
but for some reason when I save it saves "player_name" in "variables" dict, but it don't load it on load.
On Save:
```
version (type:text), (variable:0.9.0)
test_bool (type:var), (variable:False)
test_float (type:var), (variable:10)
story_state (type:text), (variable:start)
test_list (type:list), (variable:[1, 3, 7])
test_val (type:var), (variable:2)
player_name (type:text), (variable:vxvxv)
```
On Load:
```
version (type:text), (variable:0.9.0)
test_bool (type:var), (variable:False)
test_float (type:var), (variable:10)
story_state (type:text), (variable:test variables 0)
alice (type:character), (variable:[Node:2472])
rench (type:character), (variable:[Node:2489])
test_list (type:list), (variable:[1, 3, 7])
```

**Comment by MatiasVME** [comment]
Hi, there. 

I'd have to see what's going on with the encryption mode.

You mean like this?

alice (type:character), (variable:[Node:2472])
rench (type:character), (variable:[Node:2489])

That's because godot does not support default serialization of Nodes or Objects.

**Comment by Jeremi360** [comment]
I just fix problem with "player_name" variable.

I don't know why it save characters in `saveflie()` I have:
```
if v.type in ["node", "character"]:
			continue
```
so it should skip it

**Comment by MatiasVME** [comment]
It is that the reference is at runtime. But if you restart the application, the "saved" nodes or objects will not be accessible.

**Comment by Jeremi360** [comment]
Yes I know that. `continue` keyword should cause skipping "characters" and "nodes" on saving

**Comment by MatiasVME** [comment]
Mmm, you could try that:

![screenshot_20180602_131108](https://user-images.githubusercontent.com/342117/40878944-a50d488a-6666-11e8-9acb-a88dabc5686a.png)

In my case, all are dictionaries. Type 18

**Comment by MatiasVME** [comment]
Mmm, but thats is work fine, I think..

vars_to_save: ((type:list), (variable:[1, 3, 7]):(type:list), (variable:[1, 3, 7])), ((type:text), (variable:0.9.0):(type:text), (variable:0.9.0)), ((type:text), (variable:test variables 0):(type:text), (variable:test variables 0)), ((type:var), (variable:10):(type:var), (variable:10)), ((type:var), (variable:False):(type:var), (variable:False))

**Comment by Jeremi360** [comment]
I add saving for "node" and "character" using `inst2dict()`.
Now we only have to fix encryption mode:
![image](https://user-images.githubusercontent.com/1294815/40884058-ef1eea5a-670b-11e8-981e-f41dc6ab98f3.png)

**Comment by MatiasVME** [comment]
You can tell me how I can replicate the error with the encrypted data. The last tests I did worked well. Maybe if you could record a video of the error :D . Well, if it's not too much trouble.

I didn't know inst2dict()

**Comment by Jeremi360** [comment]
![peek 2018-06-04 17-49](https://user-images.githubusercontent.com/1294815/40927727-bee517dc-681f-11e8-9566-498c5c7adf99.gif)

**Comment by MatiasVME** [comment]
Is a video --> [ren.zip](https://github.com/jeremi360/Ren/files/2070248/ren.zip)

I don't have the same problem :confused:

**Comment by Jeremi360** [comment]
Now it's working!
I just had to remove *.local/share/godot/app_userdata/Ren* :)

**Comment by Jeremi360** [comment]
@MatiasVME Save/Load is Broken :(

**Comment by Jeremi360** [comment]
I fixed Save/Load, but it going one step after load - testing branch: https://github.com/jeremi360/Ren/tree/testing

**Comment by Jeremi360** [comment]
Marged with working version of Save/Load system from testing branch
