### ISSUE TITLE
Right mouse button working in MainMenu causes a bug

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/Rakugo-archive#170]
Reported by ![image](https://user-images.githubusercontent.com/1294815/66105812-c1d3b400-e5bc-11e9-95df-7c9e57e5795b.png) trough our discord.
![image](https://user-images.githubusercontent.com/1294815/66106132-71a92180-e5bd-11e9-92af-1b88986a13ee.png)

**Comment by jebedaia360** [comment]
fixed in #175 , [Core#12](https://github.com/rakugoteam/Rakugo-Core/pull/12), [GUI#b261b5f](https://github.com/rakugoteam/Rakugo-GUI-VN/commit/b261b5f876f70b37d29010e4695808cf485d1927)

**Comment by Jeremi360** [comment]
closed by mistake

**Comment by Jeremi360** [comment]
fixed in [GUI#e6d5a3c](https://github.com/rakugoteam/Rakugo-GUI-VN/commit/50381e0b4c983213b0453a2fb2e5a98b7201b9e5)
