### ISSUE TITLE
Working options

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/Rakugo-archive#18]
Like Ren'Py preferences.
![Exmaple from renpy docs](https://www.renpy.org/doc/html/_images/slider_preferences.jpg)

**Comment by MatiasVME** [comment]
Hi,

You could save that to a Config file??

**Comment by Jeremi360** [comment]
I always want to use config file for this

**Comment by Jeremi360** [comment]
*Preferences* was change into *Options*.

**Comment by Jeremi360** [comment]
Ported 2D graphics settings from my other project #50 :
[Platfromer 2D tutorial](https://github.com/jeremi360/godot-tuts/tree/master/Platfromer%202D/ui/OptionsPage)
![image](https://user-images.githubusercontent.com/1294815/48677303-1de34480-eb73-11e8-8026-03da112364f1.png)

**Comment by Jeremi360** [comment]
Ported Music/Sound settings from my other project:
[Platfromer 2D tutorial](https://github.com/jeremi360/godot-tuts/tree/master/Platfromer%202D/ui/OptionsPage)
![image](https://user-images.githubusercontent.com/1294815/48973039-11f5f780-f037-11e8-894e-e008d751273f.png)

**Comment by Jeremi360** [comment]
Now only save and load  for options need to be added.

**Comment by Jeremi360** [comment]
I need add skipping, auto and text settings.

**Comment by Jeremi360** [comment]
RenTimer Node could be handy  #71

**Comment by Jeremi360** [comment]
Almost all settings done in #74, now I do skipping after_choices.
And saving options.
![image](https://user-images.githubusercontent.com/1294815/50387271-84223080-06f8-11e9-8ed8-cf57a62b4835.png)

**Comment by Jeremi360** [comment]
Because of this [bug this]( #68 ) 2 options will be not implemented for now and hidden:
- Skipping unseen text
- Continue skipping after choice

**Comment by Jeremi360** [comment]
Load/save options works - done in #83
