### ISSUE TITLE
Show and Hide statements

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/Rakugo-archive#24]
Show and Hide statements like in Ren'Py
Show and Hide statements with support for Node2D, Control, VisualInstance

**Comment by Jeremi360** [comment]
It don't have support for states (ren'py version has) and Character Nodes for example:
`show("elie", ["sad"])` - show elie and send signal `on_state` with state `["sad"]` - to do
Also add support for custom RenNode - normal node, but with signal `on_state`

**Comment by deep-gaurav** [comment]
Can we just emit_signal a signal on_show with an optional arguement like [state] for eg ["sad"]?

**Comment by Jeremi360** [comment]
yes, it will be that way

**Comment by Jeremi360** [comment]
Now its works with design for it Custom Nodes:

- Screen - to show controls- RenNode2D
- RenVisualInstance - to show 3D
- Character - non-visual version of Character
- Character2D
- Character3D
