### ISSUE TITLE
Spaces and tabs mixed together.

### ISSUE THREAD

**Issue by Sslaxx** [rakugoteam/Rakugo-archive#242]
As of the 2.0.8f3 releases.

Godot 3.2 is coming up with the unhelpful "unable to load addon script" dialogue box. *This is reported on the Godot GH at https://github.com/godotengine/godot/issues/30377*

According to the console, the actual problem is `SCRIPT ERROR: GDScript::reload: Parse Error: Parse error: Spaces used before tabs on a line`.

These errors occur in the files `/addons/Rakugo/plugin.gd` and `/game/scenes/Start/later.gd` (for "The Question"). There may be other places where mixed tabs and spaces occur.

**Comment by Jeremi360** [comment]
@Sslaxx 
2.0.8f3 is only tested for 3.1.2, but you are right I should also test it on 3.2.
2.1.00 is tested on 3.2
I will fix this as soon as possible.

**Comment by Jeremi360** [comment]
@Sslaxx fixed in #243, #244, #245, #246
I will make new releases as soon as possible.
You can clone and switch to **the-question-1.2** branch to test it.
