### ISSUE TITLE
Background music in The Question is playing as mono

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/Rakugo-archive#253]
When I play *res://game/illurock.ogg* in editor is playing as stereo, but in game is playing as a mono.
When I open it in Audacity I saw that it was mono so I change it to stereo as *res://game/illurock-stereo.ogg* and set to it as stream of **$BGMusic** in *res://game/scenes/Start/start.tscn*.
But it still plays as mono in game :disappointed: 

Realted files:
- https://github.com/rakugoteam/Rakugo/blob/the-question-1.2/game/scenes/Start/start.tscn
- https://github.com/rakugoteam/Rakugo/blob/the-question-1.2/game/illurock-stereo.ogg
- https://github.com/rakugoteam/Rakugo/blob/the-question-1.2/game/illurock-stereo.ogg.import
- https://github.com/rakugoteam/Rakugo/blob/the-question-1.2/default_bus_layout.tres

**Comment by jebedaia360** [comment]
I will try different backgournd music

**Comment by Jeremi360** [comment]
I fix it by chaning type of *BGMPlayer* to *RakugoAudioPlayer*
And change `pause_mode` to `process`.
