### ISSUE TITLE
Freeze on "The Question", asking right away/interactive book.

### ISSUE THREAD

**Issue by Sslaxx** [rakugoteam/Rakugo-archive#256]
**Describe the bug**
When you decide to talk to Sylvie right away, and then select the "It's an interactive book" option, the game will halt at the dialogue "I'd love to!". No apparent error messages on the console/terminal.

On further inspection, adding a `print` statement after the `s.say({"what":  "I'd love to!"})` line indicates that the state appears to loop at least twice before freezing.

Placing the print statement in this block indicates that it gets to this point, but the `jump` statement appears to not work.
```
	if next_state():
		jump("Start", "marry", "marry")
```

**To Reproduce**
1. Start "The Question"
2. Click on "ask her right away"
3. Click on "It's an interactive book"

**Expected behavior**
That the game would proceed to the next scene/end game screens.

**Runtime (please complete the following information):**
 - Godot version 3.2
 - Rakugo Version 2.0.8

On an unrelated (?) note,  `/game/scenes/Start/later.gd` still has mixed spaces and tabs at line 18.

**Comment by Jeremi360** [comment]
Thanks for report @Sslaxx, I will check it out.

`On an unrelated (?) note, /game/scenes/Start/later.gd still has mixed spaces and tabs at line 18.`
Something go wrong on merge then, I will fix this.

**Comment by jebedaia360** [comment]
@Sslaxx 
After #257 it and more should be fixed at `the-question-1.2`

**Comment by Jeremi360** [comment]
@Sslaxx 
After #259 it and more should be fixed at `the-question-1.2`
