### ISSUE TITLE
Poor readibility in places with "The Question".

### ISSUE THREAD

**Issue by Sslaxx** [rakugoteam/Rakugo-archive#262]
**Describe the bug**
Choice of font and font colours render the text illegible in places in "The Question".

**Expected behavior**
Readable, legible fonts/colours (possibly using font outlines).

**Screenshots**
![Poor_Readability](https://user-images.githubusercontent.com/324679/74084454-36d16180-4a67-11ea-8698-0308419f2905.jpg)

**Runtime (please complete the following information):**
 - Godot version 3.2
 - Rakugo Version 2.0.8

**Comment by Jeremi360** [comment]
@Sslaxx
I know about this it should be already fixed in branch `the-question-1.2`,but I will check it again.

**Comment by Jeremi360** [comment]
@Sslaxx It is fixed
![image](https://user-images.githubusercontent.com/1294815/74185902-d9e1d100-4c49-11ea-9063-14ff9b89edbf.png)

**Comment by Jeremi360** [comment]
Now fixed for 2.1.00
