### ISSUE TITLE
"The Question" 1.2f4 - fatal error, main.gd.

### ISSUE THREAD

**Issue by Sslaxx** [rakugoteam/Rakugo-archive#279]
**Describe the bug**
When loading "The Question", Godot reports `SCRIPT ERROR: GDScript::reload: Parse Error: The identifier "RakugoMenu" isn't a valid type (not a script or class), or couldn't be found on base "self".` - if you try to then run the project, you get the same error on the Debugger tab of Godot's editor; the project does not run.

**To Reproduce**
1. Load the project.
2. Run it.

**Expected behavior**
"The Question" running.

**Runtime (please complete the following information):**
 - Godot version 3.2
 - Rakugo Version 2.0.8f4 ("The Question" 1.2f4)

EDIT: Reinstating the `class_name RakugoMenu` in `rakugo_menu.gd` (and then restarting the editor) resolved this issue.

Also, does https://github.com/rakugoteam/Rakugo/pull/276 fix this?

**Comment by Jeremi360** [comment]
@Sslaxx 
Sorry, I uploaded wrong zips to github - I just upolade correct ones it now it should worked.
And yes #276 fix this!
But not in this way:
`Reinstating the class_name RakugoMenu in rakugo_menu.gd (and then restarting the editor) resolved this issue.` - The are two _RakugoMenu_ classes in 2.0.8: _RakugoMenuV_ and _RakugoMenuH_ - clean _RakugoMenu_ is not so useful in this version - but it is totally changed in 2.1.00 .
