### ISSUE TITLE
2D Art Assets Requests and Feedback

### ISSUE THREAD

**Issue by Title-Pending** [rakugoteam/Rakugo-archive#34]
Hey all, I started a small project for 2D art. First, I'm working on visual novel assets. 

[Characters](https://opengameart.org/content/for-godot-3-visual-novel-project)

Backgrounds (Coming Soon)

I also started a project in this Git ;)

Edited: I'm  a decent artist, but I'm just starting to learn GDscript. As this may help me, I'm willing to help ;)

**Comment by Jeremi360** [comment]
Hi, I will gladly accept your help.
Here is your invitation: [https://github.com/jeremi360/Ren/invitations](https://github.com/jeremi360/Ren/invitations).
I saw your youtube video :)

Ren works way that you have main `Ren` singleton. 
And every statements is crate node and then they are _run_ (`enter` func)  in correct order and
signals about it are received by gui in _scenes/gui/Window.tscn_.

Please contact with me on repo room: [https://gitter.im/jeremi360/Ren-GD](https://gitter.im/jeremi360/Ren-GD).
