### ISSUE TITLE
How can I test the project?

### ISSUE THREAD

**Issue by MatiasVME** [rakugoteam/Rakugo-archive#36]
How can I test the project?

**Comment by Title-Pending** [comment]
You can download it, and open it in Godot 3. Or, you can download github and run it from that.

**Comment by Jeremi360** [comment]
for now only "Q.Load" and "Q.Save" works

**Comment by MatiasVME** [comment]
But what a scene I run to test the problem with the Persistence plugin?

**Comment by Jeremi360** [comment]
Just run project or examples/test.tscn, Persistence node is part of singleton Ren witch is addons/Ren/Ren.tscn

**Comment by MatiasVME** [comment]
But I opened those scenes and I didn't see anything, I don't know how to test. =S

**Comment by Jeremi360** [comment]
For example:
![peek 2018-05-31 21-58](https://user-images.githubusercontent.com/1294815/40805261-fe6700fa-651d-11e8-8eb5-7b5d7afa4fec.gif)

**Comment by MatiasVME** [comment]
:open_mouth: I can't see that screen :confused:

Which version of godot are you using?

**Comment by Jeremi360** [comment]
I use godot 3.0.1.
You don't see it in examples/test.tscn or in Ren.tscn, because it is another singleton scenes/gui/Window.tscn

**Comment by MatiasVME** [comment]
Mmm, has broken dependencies.

![screenshot_20180531_161101](https://user-images.githubusercontent.com/342117/40805861-a52ffc1a-64ed-11e8-9ab6-aa33c7fadd86.png)

**Comment by Jeremi360** [comment]
I don't have any new to commit Just download new version

**Comment by MatiasVME** [comment]
I'm gonna try to fix it. :smile:
