### ISSUE TITLE
Cannot run example game in Godot 3.2.2 RC 

### ISSUE THREAD

**Issue by triptych** [rakugoteam/Rakugo-archive#364]
**Describe the bug**
Game fails to start in debug mode due to GDScript error

**To Reproduce**
1) get Godot 3.2.2 RC 1
2) get "The Question : Rakugo Edition" from itch.io
3) open "The Question: Rakugo Edition" from the Godot project viewer after scanning for it
4) press play arrow in upper right

**Expected behavior**
Expect the example game to run
**Screenshots**
![Godot_v3 2 2-rc1_win64_agusReviL3](https://user-images.githubusercontent.com/8691/84533829-c436f380-ac9d-11ea-9896-1856008334a0.png)

**Runtime (please complete the following information):**
 - Godot version 3.2.2 rc-1 windows 64bit non-c# 
 - Rakugo Version 2.1.00
- The-Question-1.4.1 from itch.io

**Additional context**
Parser Error: The variable type cannot be inferred because its value is "null".
in save_file.gd 4 at function invoke 
var r := Rakugo

**Comment by triptych** [comment]
I tried getting the sample project from the repo but that failed to open at all:

Unable to load addon script from path: 'res://addons/Rakugo/plugin.gd' There seems to be an error in the code, please check the syntax.
( https://github.com/rakugoteam/Rakugo/tree/the-question-1.2 )

**Comment by triptych** [comment]
I also tried from "the-question" branch with the same results as above

**Comment by jebedaia360** [comment]
I don't know why it give you this bug - I don't tried yet to run in on Godot 3.2.2 RC 1 .
I already have made a new release, just don't update jest links on itch.io - first I want to make video how to update to it from previous version.
Maybe this will work with Godot 3.2.2 RC 1, if not try with Godot 3.2.1:
https://github.com/rakugoteam/Rakugo/releases/tag/v2.1.02

**Comment by Jeremi360** [comment]
@triptych I don't know why it give you this bug: 
```
Parser Error: The variable type cannot be inferred because its value is "null".
in save_file.gd 4 at function invoke
var r := Rakugo
```
I don't tried yet to run in on Godot 3.2.2 RC 1 .
Also strange how you have 2.1.00? there is 21.01 on itch.io - with many fixes.
And I already have made even newer a new release, just don't update jest links on itch.io
First I want to make video how to update to it from previous version.
Maybe this will work with Godot 3.2.2 RC 1, if not try with Godot 3.2.1:
https://github.com/rakugoteam/Rakugo/releases/tag/v2.1.02

**Comment by triptych** [comment]
Thank you! I will try this out on both 3.2.2 RC 1 and 3.2.1 and respond here.

**Comment by jebedaia360** [comment]
@triptych Hey! It was 6 days already. So it works or not?

**Comment by Jeremi360** [comment]
@triptych I just found out why It can't works. I working of fixing it just now.

**Comment by Jeremi360** [comment]
@triptych The newest *Rakugo*/*The Question* update should fix this bug finally.
https://github.com/rakugoteam/Rakugo/releases/tag/v2.1.03

**Comment by songproducer** [comment]
I just tried to open Rakugo-2.1.03 and The-Question-1.4.2 in Godot 3.2.2 but still got the same error

**Comment by Jeremi360** [comment]
@songproducer @triptych I don't have this error under 3.2.1 :/
I will soon check Rakugo on 3.2.2 and will try to fix it as soon as possible.

**Comment by songproducer** [comment]
I also had the same error on 3.2.1

**Comment by Jeremi360** [comment]
@songproducer Okay, I think I know what may be causing this bug, I fixing it now :)

**Comment by Jeremi360** [comment]
Sorry, github now auto close issue if you link it to pull request with "fix" in name.
PR #372 should fix this error @triptych @songproducer - I will soon attach here new relase so you can test it.

**Comment by triptych** [comment]
Thanks! really want to try this out

**Comment by Jeremi360** [comment]
This should work, @triptych , @songproducer , please test:
https://github.com/rakugoteam/Rakugo/releases/tag/v2.1.04

**Comment by triptych** [comment]
Sure, will check it out!

**Comment by songproducer** [comment]
I get:
>Parser Error: Variable "subquest" already defined in the scope (at line 60).

**Comment by Jeremi360** [comment]
> I get:
> 
> > Parser Error: Variable "subquest" already defined in the scope (at line 60).

Strange I already fix this, something must go wrong when I replaces files in releases :/

**Comment by Jeremi360** [comment]
@triptych @songproducer 
Now it should work: https://github.com/rakugoteam/Rakugo/releases/tag/v2.1.04-RC2

**Comment by songproducer** [comment]
Thanks! It works for me now

**Comment by Jeremi360** [comment]
Nice to here that @songproducer :)
So it works for you also @triptych ?

**Comment by triptych** [comment]
I will try tonight when I can use my home laptop. I will update here yes or no.

**Comment by triptych** [comment]
I will update in a few hours - had network issues add day.

**Comment by triptych** [comment]
So, I went to the link  you sent above - with the tag v2.1.04-RC2
I downloaded this file https://github.com/rakugoteam/Rakugo/releases/download/v2.1.04-RC2/The-Question-1.4.3.zip
And unzipped it
I then loaded the release godot 3.2.2.
I hit scan and chose the directory I had just created.
I changed to the 2d view and hit the play button .
The game comes up with the same error.

![Godot_v3 2 2-rc4_win64_np36numOfj](https://user-images.githubusercontent.com/8691/86251557-df8f7300-bb66-11ea-8296-d88f466eb870.png)

Did you update the engine perhaps and not the sample game?

**Comment by Jeremi360** [comment]
@triptych I probably upload wrong file I will fix it soon.

**Comment by Jeremi360** [comment]
@triptych @songproducer Now It works, and I also found other 3 small bugs that I fixed also.
https://github.com/rakugoteam/Rakugo/releases/tag/v2.1.04-RC3

**Comment by triptych** [comment]
I can confirm this RC3 version works for me!

**Comment by Jeremi360** [comment]
@triptych Grate then I make of it official release soon :)
