### ISSUE TITLE
Add Statements and/or Nodes to work with sound and music

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/Rakugo-archive#39]
Like in title

**Comment by jeremi360** [comment]
After experimenting with godot sound system is clear that we don't need any special statements for playing sond/music in Ren.

**Comment by Jeremi360** [comment]
It will be node *RenAudioPlayer* based on *AudioStreamPlayer* and statement *play_audio* working together in similar way like *RenAnimPlayer* and statement *play_anim* are working.

**Comment by Jeremi360** [comment]
Done in #61
