### ISSUE TITLE
Fresh install fails for Godot 3.2.3

### ISSUE THREAD

**Issue by zaknafean** [rakugoteam/Rakugo-archive#393]
**Describe the bug**
I wanted to try out the plugin, and despite the lack of instructions, figured I could likely just copy what was in the addon folder and give it a shot like most plugins. This failed very badly, looking for many dependencies in folders that were definitely not part of the 'addon' files. 

**To Reproduce**
1. Copy addons folder to your local projects addon folders
2. Try to activate the plugin

**Expected behavior**
I'd expect things to be self contained and be able to try things out within an existing project. If this isn't really meant for existing projects that would be something nice to document.

**Runtime (please complete the following information):**
 - Godot version: 3.2.3
 - Rakugo Version:  2.0.8 ? (whatever I get when I hit download zip)

**Additional context**
Not much else to say. This looks like a project I'd really want to use for my point and click, but I'll have to search some more for now.

**Comment by Jeremi360** [comment]
Hi, @zaknafean and @rolevax

> Copy addons folder to your local projects addon folders

So @zaknafean Rakugo is gui template + addon and is intended to be used this way only.

> Rakugo Version: 2.0.8 ? (whatever I get when I hit download zip)

Always download version form release page. - some time by mistake I can commit some wip in to master.  

Now I and @Vaasref are in process rewritting all project. It propably will be ready at next month. 

If you want to check out beta version:

1.  join our discord: https://discord.gg/K9gvjdg
1. and download/frok @Vaasref  version: https://github.com/Vaasref/Rakugo

**Comment by Vaasref** [comment]
@zaknafean 
Yup, this is one of the reason I redesigned Rakugo and rewrote most of it at that point.

In the upcoming version, currently in dev' on my fork (it is not in beta at all, it would be closer to alpha) there is not much left from this repo.
The job of untying the core (addons/rakugo) and the rest is also mostly done at that point. Although it is primarily intended to be used alongside its template, it is possible to use it without thanks to the new structure, as long as you handle all the GUI.

However, don't expect to just drop the plugin in your project and have it working without some setting up few things.
The default values are set to be the default case use of Rakugo, so with the template, so you need to change them.
There is also some autoloads to add to your project.

**Comment by zaknafean** [comment]
Pretty satisfied with these answers. Me using the tool improperly is not an issue in the github sense! Just a personal one.
