### ISSUE TITLE
what do you have in mind for the rpg system?

### ISSUE THREAD

**Issue by MatiasVME** [rakugoteam/Rakugo-archive#42]
I have an RPG system but it is not complete. It's a plugin for the godot 2 version, I'm using it for my game.

The characteristics that it has is that it solves a little the logic of the items and inventory in a generic way.

At the moment I am working alone on the godot 2 version of the plugin, the godot 3 version I have to adapt from 2.

The plugin is called RPGElments. It is not complete, but can be completed :)
https://github.com/MatiasVME/RPGElements/tree/for-godot-2 <-- this is the branch

**Comment by MatiasVME** [comment]
Here a inventory in action --> https://youtu.be/iznFdzrFA68

**Comment by Jeremi360** [comment]
Nice, I think we can try to use this to don't reinvent the wheel.
For RPG system I want to have:
- quests (almost done),
- RPGCharacter (that inherits from or have some of RenChracter), 
- Invetory & equimpent slots, skills and leveling, 
- some base stuff to make easy to make turn based combat - is this to mach or not?

**Comment by MatiasVME** [comment]
it is better to have a system more adapted to Ren
