### ISSUE TITLE
Skipping don't  skip more that one story_state

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/Rakugo-archive#68]
Skipping don't skip all story steps with say statement even if they are not in global history.

**Comment by Jeremi360** [comment]
Fixed in #69

**Comment by Jeremi360** [comment]
I was wrong #69 didn't fix it :(

**Comment by jeremi360** [comment]
Bug is probably here ( line 559 in _addons/Ren/main.gd_):
```
func current_statement_in_global_history():
	var r = true
	var i = 0
	var hi_item = current_statement.get_as_history_item()

	if not current_statement.kwargs.add_to_history:
		i = 1
		r = true
		prints(hi_item, "r =", str(r), "i =", str(i))
		return r

	if not hi_item.has("state"):
		i = 2
		r = true
		prints(hi_item, "r =", str(r), "i =", str(i))
		return r

	for hx_item in history:
		if hx_item.state != hi_item.state:
			continue

		var x_statement = hx_item.statement
		var c_statement = hi_item.statement
		if x_statement.type != c_statement.type:
			i = 3
			r = false
			prints(hi_item, "r =", str(r), "i =", str(i))
			return r

		for k in x_statement.kwargs.keys():
			if c_statement.kwargs[k] != x_statement.kwargs[k]:
				i = 3
				r = false
				prints(hi_item, "r =", str(r), "i =", str(i))
				return r
	
	i = 4
	r = false
	prints(hi_item, "r =", str(r), "i =", str(i))
	return r
```

**Comment by girng** [comment]
just posting because we got similar avatars

nice to meet you, godot friend

**Comment by Jeremi360** [comment]
No skipping is always disabled - I don't know why this is happens from out put I get some times true or false so it should works :(

**Comment by Jeremi360** [comment]
I don't have any idea how to fix it so for now skipping button
and its options will be hidden in standard relase of addon ( #76 ) .
Also Fixing this bug is now removed from [Milestone 1.0.0](https://github.com/jeremi360/Ren/milestone/1).

**Comment by Jeremi360** [comment]
If this will be fixed then this must be implemented after:
- Skipping unseen text
- Continue skipping after choice
- Tab - press to toggle skipping
- Ctrl - hold to continue skipping

**Comment by Jeremi360** [comment]
Making #95 will make it easier to fix

**Comment by Jeremi360** [comment]
After last changes skipping can be rewrite and probably working

**Comment by Jeremi360** [comment]
Now finally I made that now history is stored in way ` {["scene_id", "node_name", "dialog_name", story_step]:{"type":type, "parameters": parameters}}` so it should be easy to make skipping.

**Comment by Jeremi360** [comment]
Skipping finally works :D
![skipping](https://user-images.githubusercontent.com/1294815/58781093-311fa400-85db-11e9-8f2b-c53a0c7031a2.gif)
