### ISSUE TITLE
Add support to write dialogs in JSON

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/Rakugo-archive#78]
Add support to write dialogs in JSON like here: 
[https://www.youtube.com/watch?v=8HOmLNuuccs](https://www.youtube.com/watch?v=8HOmLNuuccs)

**Comment by jeremi360** [comment]
I think JSON support is not needed - RenScript is similar,  easier readable and easier to use

**Comment by Jeremi360** [comment]
After some time I think that we should add support for writing dialogs in JSON
