### ISSUE TITLE
Update to Godot 3.1

### ISSUE THREAD

**Issue by ivandardi** [rakugoteam/Rakugo-archive#81]
Since Godot is currently in 3.1 beta, with 3.1 scheduled to launch at the end of January, I think it would be interesting to update Ren to work with 3.1 already. I am willing to help with it.

**Comment by Jeremi360** [comment]
Hi, @ivandardi 
I want to make it compatbile with 3.1 - it have fatures that make writing advanced addons esier, but also this will brake compatbile with 3.0 so we can do to things:
- try to make it compatblie with both
- make one branch for 3.0 and other for 3.1

**Comment by Jeremi360** [comment]
![image](https://user-images.githubusercontent.com/1294815/51001077-2fbbe500-152f-11e9-8adc-dc65375002d1.png)

**Comment by Jeremi360** [comment]
We need refactorings, there's a few things that need to be done:
1. @ivandardi  need to do an english review and rewrite most of the docs comments.
2. Better naming of some things. there's a few places where the names are too generic and they make understanding hard.
3. Make all script that aren't examples use optional typing
4. All Custom nodes and all scripts that inhertits inside Ren use `class_name` feature

Here is link to GDScript 3.1 optional typing and `class_name` features: [https://www.gdquest.com/tutorial/game-design/godot/gdscript/typed-gdscript/](https://www.gdquest.com/tutorial/game-design/godot/gdscript/typed-gdscript/)

**Comment by Jeremi360** [comment]
*addons/Ren/statics/text.gd* - use optional typing
RenBaseButton, RenButton, RenChoiceButton - use class_name feature

**Comment by Jeremi360** [comment]
All Ren custom nodes, that can, use class_name - done in #88
Nodes that are dependency of Ren use class_name too - done in #89

**Comment by Jeremi360** [comment]
All Ren Types Use class_name - done in #90

**Comment by Jeremi360** [comment]
All RenTypes use class_name - done in  #91

It means that 4th point of our refactoring is done: 
*All Custom nodes and all scripts that inherits inside Ren use class_name feature*

**Comment by Jeremi360** [comment]
All scenes was updated to use new nodes  - done in #92
Also now Persistence and JSONBeautifier use optional typing - done in #92

**Comment by Jeremi360** [comment]
All Ren Object types and Statements use optional typing - done in #96

**Comment by Jeremi360** [comment]
![zrzut ekranu z 2019-01-27 17-06-44](https://user-images.githubusercontent.com/1294815/51803520-4c0d9080-2256-11e9-98cd-6088a65bdc58.png)
Done in #98

**Comment by Jeremi360** [comment]
I made that now all gui and main.gd use optional typing

**Comment by Jeremi360** [comment]
#95 is done :smile: - now story step is auto `int `and menu is uses `jump()`

**Comment by Jeremi360** [comment]
Why it is still open ? closing.
